//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationLog
    {
        public int log_id { get; set; }
        public Nullable<System.DateTime> log_date { get; set; }
        public string ip_addr { get; set; }
        public string view_name { get; set; }
        public Nullable<int> member_seq { get; set; }
        public Nullable<int> club_id { get; set; }
    }
}
