//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubOfficer
    {
        public Nullable<int> fiscal_year { get; set; }
        public int member_seq { get; set; }
        public int officer_id { get; set; }
        public int club_officer_id { get; set; }
        public Nullable<int> club_id { get; set; }
        public Nullable<int> seq_no { get; set; }
    
        public virtual Officer Officer { get; set; }
        public virtual Member Member { get; set; }
        public virtual Club Club { get; set; }
    }
}
