//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeDetail
    {
        public int committee_detail_id { get; set; }
        public Nullable<int> committee_id { get; set; }
        public Nullable<int> officer_id { get; set; }
        public Nullable<int> fiscal_year { get; set; }
        public Nullable<int> member_seq { get; set; }
        public Nullable<int> club_id { get; set; }
        public Nullable<int> seq_no { get; set; }
    
        public virtual Committee Committee { get; set; }
        public virtual CommitteeOfficer CommitteeOfficer { get; set; }
        public virtual Club Club { get; set; }
        public virtual Member Member { get; set; }
    }
}
