//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDetail
    {
        public int course_detail_id { get; set; }
        public Nullable<int> fiscal_year { get; set; }
        public Nullable<int> result { get; set; }
        public string remark { get; set; }
        public Nullable<int> member_seq { get; set; }
        public Nullable<int> club_id { get; set; }
        public Nullable<int> course_id { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Club Club { get; set; }
        public virtual Member Member { get; set; }
    }
}
