//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.ClubOfficer = new HashSet<ClubOfficer>();
            this.CommitteeDetail = new HashSet<CommitteeDetail>();
            this.CourseDetail = new HashSet<CourseDetail>();
            this.MemberMovement = new HashSet<MemberMovement>();
            this.ZoneOfficer = new HashSet<ZoneOfficer>();
            this.RegionOfficer = new HashSet<RegionOfficer>();
            this.TUser = new HashSet<TUser>();
        }
    
        public Nullable<int> member_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public string member_address_eng { get; set; }
        public string email { get; set; }
        public string cell_phone { get; set; }
        public Nullable<int> birth_year { get; set; }
        public string occupation { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
        public Nullable<int> club_id { get; set; }
        public int member_seq { get; set; }
        public Nullable<int> membership_type { get; set; }
        public string first_name_eng { get; set; }
        public string last_name_eng { get; set; }
        public string member_address_thai { get; set; }
        public byte[] image { get; set; }
        public string sponsor_name { get; set; }
        public Nullable<System.DateTime> upd_date { get; set; }
        public string charter_flag { get; set; }
        public Nullable<int> member_sts { get; set; }
        public string line_id { get; set; }
    
        public virtual Club Club { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubOfficer> ClubOfficer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommitteeDetail> CommitteeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseDetail> CourseDetail { get; set; }
        public virtual MembershipType MembershipType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberMovement> MemberMovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZoneOfficer> ZoneOfficer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegionOfficer> RegionOfficer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUser> TUser { get; set; }
    }
}
