//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.ClubOfficer = new HashSet<ClubOfficer>();
            this.CommitteeDetail = new HashSet<CommitteeDetail>();
            this.CourseDetail = new HashSet<CourseDetail>();
            this.TUser = new HashSet<TUser>();
            this.MemberMovement = new HashSet<MemberMovement>();
            this.ZoneClub = new HashSet<ZoneClub>();
            this.ZoneOfficer = new HashSet<ZoneOfficer>();
            this.RegionOfficer = new HashSet<RegionOfficer>();
        }

        [Display(Name = "รหัสสมาชิก")]
        [Required(ErrorMessage = "บันทึกรหัสสมาชิก")]
        public Nullable<int> member_id { get; set; }

        [Display(Name = "ชื่อ")]
        public string first_name { get; set; }

        [Display(Name = "นามสกุล")]
        public string last_name { get; set; }

        [Display(Name = "เพศ")]
        public string gender { get; set; }

        [Display(Name = "ที่อยู่(อังกฤษ)")]
        public string member_address_eng { get; set; }

        [Display(Name = "email")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]
        public string email { get; set; }

        [Display(Name = "เบอร์มือถือ")]
        public string cell_phone { get; set; }

        [Display(Name = "ปีเกิด")]
        public Nullable<int> birth_year { get; set; }

        [Display(Name = "อาชีพ")]
        public string occupation { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d MMM yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "วันที่เป็นสมาชิก")]
        [Required(ErrorMessage = "บันทึกวันที่เป็นสมาชิก")]
        public Nullable<System.DateTime> join_date { get; set; }

        [Display(Name = "สโมสร")]
        [Required(ErrorMessage = "บันทึกสโมสร")]
        public Nullable<int> club_id { get; set; }

        public int member_seq { get; set; }

        [Display(Name = "ประเภทสมาชิก")]
        [Required(ErrorMessage = "บันทึกประเภทสมาชิก")]
        public Nullable<int> membership_type { get; set; }

        [Display(Name = "ชื่อ(อังกฤษ)")]
        [Required(ErrorMessage = "บันทึกชื่ออังกฤษ")]
        public string first_name_eng { get; set; }

        [Display(Name = "นามสกุล(อังกฤษ)")]
        [Required(ErrorMessage = "บันทึกนามสกุลอังกฤษ")]
        public string last_name_eng { get; set; }

        [Display(Name = "ที่อยู่")]
        public string member_address_thai { get; set; }

        [Display(Name = "รูปภาพ")]
        public byte[] image { get; set; }

        [Display(Name = "ผู้แนะนำ")]
        public string sponsor_name { get; set; }
        public Nullable<System.DateTime> upd_date { get; set; }

        [Display(Name = "สมาชิกก่อตั้ง")]
        public string charter_flag { get; set; }

        [Display(Name = "สถานะสมาชิก")]
        public Nullable<int> member_sts { get; set; }

        [Display(Name = "ชื่อ นามสกุล")]
        public string full_name_eng
        {
            get { return "Lion " + first_name_eng + " " + last_name_eng; }
        }

        [Display(Name = "ชื่อ นามสกุล")]
        public string full_name_thai
        {
            get { return "ไลออน " + first_name + " " + last_name; }
        }

        [Display(Name = "ชื่อ นามสกุล")]
        public string full_name
        {
            get
            {
                if (first_name == null) { return "Lion " + first_name_eng + " " + last_name_eng; } else { return "ไลออน " + first_name + " " + last_name; }
            }
        }

        public string member_addr
        {
            get
            {
                if (member_address_eng != null) { return member_address_eng; } else { return member_address_thai; }
            }
        }

        public string genderName
        {
            get
            {

                var gName = gender == "M" ? "ชาย"
                : gender == "F" ? "หญิง" : "";
                return gName;
            }
        }
        public string charterName
        {
            get
            {

                var CharterName = charter_flag == "N" ? ""
                : charter_flag == "Y" ? "สมาชิกก่อตั้ง" : "";
                return CharterName;
            }
        }
        public string statusName
        {
            get
            {
                string tMemberSts = null;
                if (member_sts == 1)
                {
                    tMemberSts = "ปกติ";
                }
                else if (member_sts == 2)
                {
                    tMemberSts = "พ้นสภาพ";
                }
                else
                {
                    tMemberSts = "";
                }

                return tMemberSts;

            }
        }

        public virtual Club Club { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubOfficer> ClubOfficer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommitteeDetail> CommitteeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseDetail> CourseDetail { get; set; }
        public virtual MembershipType MembershipType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUser> TUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberMovement> MemberMovement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZoneClub> ZoneClub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZoneOfficer> ZoneOfficer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegionOfficer> RegionOfficer { get; set; }
    }
}
