//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMovement
    {
        public int hist_id { get; set; }
        public Nullable<System.DateTime> hist_date { get; set; }
        public Nullable<int> member_seq { get; set; }
        public Nullable<int> club_id { get; set; }
        public Nullable<int> move_sts { get; set; }
        public string comment { get; set; }
    
        public virtual Movement Movement { get; set; }
        public virtual Club Club { get; set; }
        public virtual Member Member { get; set; }
    }
}
