//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MultipleDistrict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MultipleDistrict()
        {
            this.District = new HashSet<District>();
        }

        [Display(Name = "รหัสภาครวม")]
        [Required(ErrorMessage = "บันทึกรหัสภาครวม")]
        public int multiple_district_id { get; set; }

        [Display(Name = "ภาครวม")]
        [Required(ErrorMessage = "บันทึกภาครวม")]
        public string multiple_district_name_thai { get; set; }

        [Display(Name = "ภาครวม(อังกฤษ)")]
        public string multiple_district_name_eng { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<District> District { get; set; }
    }
}
