//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Officer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Officer()
        {
            this.ClubOfficer = new HashSet<ClubOfficer>();
        }

        [Display(Name = "รหัสตำแหน่ง")]
        public int officer_id { get; set; }

        [Display(Name = "ตำแหน่ง")]
        [Required(ErrorMessage = "บันทึกตำแหน่ง")]
        public string title { get; set; }

        [Display(Name = "ประเภทตำแหน่ง")]
        [Required(ErrorMessage = "บันทุกประเภทตำแหน่ง")]
        public string officer_type { get; set; }

        [Display(Name = "ตำแหน่ง(อังกฤษ)")]
        public string title_eng { get; set; }

        [Display(Name = "ลำดับที่")]
        public Nullable<int> seq_no { get; set; }

        [Display(Name = "กลุ่ม")]
        public Nullable<int> officer_grp { get; set; }

        [Display(Name = "ประเภทตำแหน่ง")]
        public string office_type_desc
        {
            get
            {

                var gName = officer_type == "C" ? "กรรมการสโมสร"
                : officer_type == "D" ? "กรรมการภาค" : "";
                return gName;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClubOfficer> ClubOfficer { get; set; }
        public virtual OfficerGroup OfficerGroup { get; set; }
    }
}
