//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TUser
    {
        [Display(Name = "รหัสผู้ใช้")]
        [Required(ErrorMessage = "บันทึกรหัสผู้ใช้")]
        public string user_code { get; set; }

        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "รหัสผ่าน")]
        [Required(ErrorMessage = "บันทึกรหัสผ่าน")]
        public string user_pwd { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d MMM yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "วันที่เริ่มต้น")]
        public Nullable<System.DateTime> eff_date { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d MMM yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "วันที่หมดอายุ")]
        public Nullable<System.DateTime> exp_date { get; set; }

        [Display(Name = "ชื่อ-นามสกุล")]
        [Required(ErrorMessage = "เลือกชื่อ-นามสกุลผู้ใช้")]
        public Nullable<int> member_seq { get; set; }


        public Nullable<System.DateTime> upd_date { get; set; }

        [Display(Name = "บทบาท")]
        [Required(ErrorMessage = "เลือกบทบาท")]
        public string role_name { get; set; }

        [Display(Name = "บทบาท")]
        public string role_name_disp
        {
            get
            {

                var grole_name = role_name == "User" ? "ผู้ใช้งาน"
                : role_name == "Admin" ? "ผู้ดูแลระบบ" : "";
                return grole_name;
            }
        }

        public virtual Member Member { get; set; }
    }
}
