//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ZoneClub
    {
        public int zone_club_id { get; set; }

        [Display(Name = "ปีบริหาร")]
        [Required(ErrorMessage = "บันทึกปีบริหาร")]
        public Nullable<int> fiscal_year { get; set; }

        [Display(Name = "สโมสร")]
        [Required(ErrorMessage = "เลือกสโมสร")]
        public Nullable<int> club_id { get; set; }

        [Display(Name = "เขตที่")]
        [Required(ErrorMessage = "เลือกเขตที่")]
        public Nullable<int> zone_officer_id { get; set; }

        [Display(Name = "ลำดับที่")]
        [Required(ErrorMessage = "บันทึกลำดับที่")]
        public Nullable<int> club_seq { get; set; }

        [Display(Name = "ชื่อ-นาทสกุล")]

        public Nullable<int> member_seq { get; set; }

        [Display(Name = "ปีบริหาร")]
        public string fiscal_year_disp
        {
            get { return fiscal_year + "-" + (fiscal_year + 1); }
        }

        public virtual ZoneOfficer ZoneOfficer { get; set; }
        public virtual Club Club { get; set; }
        public virtual Member Member { get; set; }
    }
}
