//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneClub
    {
        public int zone_club_id { get; set; }
        public Nullable<int> fiscal_year { get; set; }
        public Nullable<int> club_id { get; set; }
        public Nullable<int> zone_officer_id { get; set; }
        public Nullable<int> club_seq { get; set; }
    
        public virtual ZoneOfficer ZoneOfficer { get; set; }
        public virtual Club Club { get; set; }
    }
}
