//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegisterLions.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ZoneOfficer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZoneOfficer()
        {
            this.ZoneClub = new HashSet<ZoneClub>();
        }

        public int zone_officer_id { get; set; }

        [Display(Name = "เขตที่")]
        [Required(ErrorMessage = "บันทึกเขตที่")]
        public Nullable<int> zone_no { get; set; }

        [Display(Name = "ปีบริหาร")]
        [Required(ErrorMessage = "บันทึกปีบริหาร")]
        public Nullable<int> fiscal_year { get; set; }

        [Display(Name = "ประธานภูมิภาค")]
        [Required(ErrorMessage = "เลือกประธานภูมิภาค")]
        public Nullable<int> region_officer_id { get; set; }

        [Display(Name = "ประธานเขต")]
        [Required(ErrorMessage = "เลือกประธานเขต")]
        public Nullable<int> member_seq { get; set; }

        [Display(Name = "ปีบริหาร")]
        public string fiscal_year_disp
        {
            get { return fiscal_year + "-" + (fiscal_year + 1); }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZoneClub> ZoneClub { get; set; }
        public virtual Member Member { get; set; }
        public virtual RegionOfficer RegionOfficer { get; set; }
    }
}
